/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/focus` | `/focus`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reminders` | `/reminders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mind/breathe` | `/mind/breathe`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mind` | `/mind`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mind/mood` | `/mind/mood`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mind/personalise` | `/mind/personalise`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mind/support` | `/mind/support`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/focus` | `/focus`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/reminders` | `/reminders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tasks` | `/tasks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mind/breathe` | `/mind/breathe`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mind` | `/mind`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mind/mood` | `/mind/mood`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mind/personalise` | `/mind/personalise`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mind/support` | `/mind/support`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/focus${`?${string}` | `#${string}` | ''}` | `/focus${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/reminders${`?${string}` | `#${string}` | ''}` | `/reminders${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tasks${`?${string}` | `#${string}` | ''}` | `/tasks${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mind/breathe${`?${string}` | `#${string}` | ''}` | `/mind/breathe${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mind${`?${string}` | `#${string}` | ''}` | `/mind${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mind/mood${`?${string}` | `#${string}` | ''}` | `/mind/mood${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mind/personalise${`?${string}` | `#${string}` | ''}` | `/mind/personalise${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mind/support${`?${string}` | `#${string}` | ''}` | `/mind/support${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/focus` | `/focus`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reminders` | `/reminders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mind/breathe` | `/mind/breathe`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mind` | `/mind`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mind/mood` | `/mind/mood`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mind/personalise` | `/mind/personalise`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mind/support` | `/mind/support`; params?: Router.UnknownInputParams; };
    }
  }
}
